title: Kevin Chan
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: Kevin Chan
tagline: Computer Science and Microbiology
about-description: Hi I'm Kevin, a fourth year honour's student majoring in Microbiology, Immunology and Computer Science at UBC. I'm interested in bioinformatics - particularly the development of bioinformatic software, algorithm development, and the usage of such software for analysis. # Add Discription
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: kevchan1@alumni.ubc.ca (change to me@kevinxchan.com?) # Add your Email address
#phone: 044 825 5523 # Add your Phone number
website: kevinxchan.com # Add your website, do not add http://
linkedin: kevinxchan # Add your Linkedin handle
github: kevinxchan # Add your Github handle
twitter: '@kevinxchan' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]

livereload: true
