title: Kevin Chan
description: Website and blog of Kevin Chan, a fourth year Computer Science and Microbiology major at UBC.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.kevinxchan.me" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: Home # top left corner of landing page (not really name)
tagline: Computer Science and Microbiology
about-description: Hi! I'm Kevin, a fourth year honour's student majoring in Microbiology, Immunology, and Computer Science at the University of British Columbia. Click around to find out more about me. # Add Discription
pic: pic_dim.png  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: kevcwchan@gmail.com # Add your Email address
#phone: 044 825 5523 # Add your Phone number
website: kevinxchan.me # Add your website, do not add http://
linkedin: kevinxchan # Add your Linkedin handle
github: kevinxchan # Add your Github handle
twitter: '@kevinxchan' # Add your Twitter handle
stackoverflow: users/10096018/kevin-chan # Add stackoverflow handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]

livereload: true
